// File generated by FlutterFire CLI.
// ---------------------------------------------------------------------------
// THIS IS A PLACEHOLDER. Run `flutterfire configure` from your project root
// (see firebase/FIREBASE_SETUP.md) — it will overwrite this file with your
// real project's credentials automatically. Do not edit this file by hand
// once that's done.
// ---------------------------------------------------------------------------
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` — see firebase/FIREBASE_SETUP.md.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFQ1zgluGW5NdUvr1-DMtgnN31XMVBw0',
    appId: '1:652663329218:web:42bb53710739be601ec65b',
    messagingSenderId: '652663329218',
    projectId: 'shopverse-15a2c',
    authDomain: 'shopverse-15a2c.firebaseapp.com',
    storageBucket: 'shopverse-15a2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Of3cbj7i-G9-S5oqKDN_mf7evRFe2S4',
    appId: '1:652663329218:android:0269dd6d0154a72d1ec65b',
    messagingSenderId: '652663329218',
    projectId: 'shopverse-15a2c',
    storageBucket: 'shopverse-15a2c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYz3yyuCtRIPNBZ_kFrp-OBIW416jaF4',
    appId: '1:652663329218:ios:1e6ec26321b69ac71ec65b',
    messagingSenderId: '652663329218',
    projectId: 'shopverse-15a2c',
    storageBucket: 'shopverse-15a2c.firebasestorage.app',
    iosBundleId: 'com.example.shopverse',
  );
}
